import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import PurpleButton from "@/components/PurpleButton/PurpleButton";
import homeBook from "@/assets/images/home_book.png";
import dealImage from "@/assets/images/deal-img.png";
import reviewLogo from "@/assets/images/review_logo.png";
import blog1 from "@/assets/images/blog-1.jpg";
import blog2 from "@/assets/images/blog-2.jpg";
import blog3 from "@/assets/images/blog-3.jpg";
import { FaHeadphones, FaLock, FaClock, FaBook } from "react-icons/fa";
export default function Home() {
  return (
    <>
      <Head>
        <title>Booker Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <section className={styles.home}>
          <div className={styles.left}>
            <h1>Kitap Summary</h1>
            <p>Күніне 20 минут ішінде жаңа білім!</p>
            <PurpleButton>Көру</PurpleButton>
          </div>

          <div className={styles.right}>
            <Image src={homeBook} className="image" alt="home" fill />
          </div>
        </section>
        <section className={styles.icons_container}>
          <div className={styles.icons}>
            <FaHeadphones />
            <div className={styles.content}>
              <h3>Формат</h3>
              <p>Аудио форматта</p>
            </div>
          </div>

          <div className={styles.icons}>
            <FaLock />
            <div className={styles.content}>
              <h3>Қорғалған </h3>
              <p>(OWASP технологиясымен)</p>
            </div>
          </div>

          <div className={styles.icons}>
            <FaClock />
            <div className={styles.content}>
              <h3>Уақыт</h3>
              <p>әрқашан хабарда болыңыз</p>
            </div>
          </div>

          <div className={styles.icons}>
            <FaBook />
            <div className={styles.content}>
              <h3>Жаңа топтама</h3>
              <p>Әр апта сайын жаңа топтама</p>
            </div>
          </div>
        </section>
        <section className={styles.newsletter}>
          <form>
            <h3>Біздің ақпараттық бюллетеньге жазылыңыз</h3>
            <input
              type="email"
              name=""
              placeholder="Email енгізіңіз"
              className={styles.box}
            />
            <PurpleButton>Жазылу</PurpleButton>
          </form>
        </section>

        <section className={styles.deal}>
          <div className={styles.content}>
            <h3>Тегін көріңіз!</h3>
            <h1>Барлық Саммари 7 күндік қол жетімділік</h1>

            <PurpleButton>7 КҮН ТЕГІН</PurpleButton>
          </div>

          <div className={styles.image}>
            <Image src={dealImage} alt="" />
          </div>
        </section>
        <section className={styles.reviews} id={styles.reviews}>
          <h1 className={styles.heading}>
            <span>Клиенттердің пікірлері</span>
          </h1>

          <div className={styles.reviews_slider}>
            <div className={styles.swiper_wrapper}>
              <div className={styles.box}>
                <Image src={reviewLogo} alt="" />
                <h3>Қайрат</h3>
                <p>
                  Мен осы интернет-дүкеннен кітаптар сатып алдым және сатып алу
                  тәжірибеме өте риза болдым. Бүкіл процесс тез және оңай болды,
                  мен кітаптарымды уақытында және тамаша күйде алдым.
                </p>
              </div>

              <div className={styles.box}>
                <Image src={reviewLogo} alt="" />
                <h3>Дастан</h3>
                <p>
                  Интернет-дүкеннің веб-сайты өте ыңғайлы және қолдануға оңай,
                  Мен іздеген кітаптарды тез таба алдым. Мен сондай-ақ қол
                  жетімді кітаптардың кең таңдауын, соның ішінде жаңа және
                  классикалық шығармаларды бағаладым.
                </p>
              </div>

              <div className={styles.box}>
                <Image src={reviewLogo} alt="" />
                <h3>Айдос</h3>
                <p>
                  Тұтастай алғанда, мен осы интернет-кітап дүкенінен сатып алу
                  тәжірибеме өте қуаныштымын және оны жақсы бағамен, жылдам
                  жеткізіліммен және тамаша қызметпен жақсы кітап іздейтіндердің
                  барлығына ұсынар едім!
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className={styles.blogs} id="blogs">
          <h1 className={styles.heading}>
            <span>our blogs</span>
          </h1>

          <div className={styles.blogs_slider}>
            <div className={styles.swipe_wrapper}>
              <div className={styles.box}>
                <div className={styles.image}>
                  <Image src={blog1} alt={""} />
                </div>
                <div className={styles.content}>
                  <h3>blog title goes here</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Optio, odio.
                  </p>
                  <PurpleButton>Read More</PurpleButton>
                </div>
              </div>

              <div className={styles.box}>
                <div className={styles.image}>
                  <Image src={blog2} alt={""} />
                </div>
                <div className={styles.content}>
                  <h3>blog title goes here</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Optio, odio.
                  </p>
                  <PurpleButton>Read More</PurpleButton>
                </div>
              </div>

              <div className={styles.box}>
                <div className={styles.image}>
                  <Image src={blog3} alt={""} />
                </div>
                <div className={styles.content}>
                  <h3>blog title goes here</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Optio, odio.
                  </p>
                  <PurpleButton>Read More</PurpleButton>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
